Divided player file into three separate components, made an interface…
shahzadhemani17/aws-amplify-signage-player pull request #1
Opened 2022-09-02 06:55 UTC by jazib-bashir

… for props, implemented previously used import/export practice

2022-09-02 07:02 UTC, shaheerizharReal commented on src/modules/player/components/SKPlayer/SKPlayer.tsx
> +      {playlists?.map((playlist, index) => {
can be better to make video, image, iframe as constants

2022-09-02 07:15 UTC, shaheerizharReal commented on src/modules/player/components/SKPlayer/SKPlayer.tsx
> +export const SKPlayer = (props: any) => {
props can have type?

2022-09-02 12:56 UTC, jazib-bashir reviewed
@umairzafar164 commit message is too long. The best practice is to write short and descriptive notes, but if you want to write all of these details, there is also a description option for commit use this, please.

```
git commit -m "Title" -m "Description ..........";
```
cc: @shaheerizharReal

2022-09-02 12:56 UTC, jazib-bashir commented on src/modules/player/components/SKPlayer/components/SKIframe.tsx
> +      style={{
@umairzafar164 move this `style` into CSS if applicable otherwise move this to constant etc because we're replicating the same code in multiple components.
cc: @shaheerizharReal

2022-09-02 12:56 UTC, jazib-bashir commented on src/modules/player/components/SKPlayer/components/SKVideo.tsx
> +  const { vidRef, index, playlist } = props;
@umairzafar164 use proper variable names
`videoRef`

2022-09-02 12:56 UTC, jazib-bashir commented on src/modules/player/components/SKPlayer/SKPlayer.tsx
> +        if (playlist.tag === "video") {
@shaheerizharReal is it possible to use `switch` here and `image` tag as a default fallback?

2022-09-02 13:02 UTC, shaheerizharReal requested changes
@umairzafar164 Please resolve these objections

2022-09-02 13:53 UTC, shaheerizharReal commented on src/modules/player/components/SKPlayer/SKPlayer.tsx
> +        if (playlist.tag === "video") {
yes. possible. @umairzafar164 let me know if need any help

2022-09-02 14:14 UTC, umairzafar164 commented on src/modules/player/components/SKPlayer/SKPlayer.tsx
> +export const SKPlayer = (props: any) => {
Yes, made a new interface for entries, Entriesmodel.

2022-09-02 14:14 UTC, umairzafar164 commented on src/modules/player/components/SKPlayer/SKPlayer.tsx
> +        } else if (playlist.tag === "image") {
enums implemented.

2022-09-02 14:14 UTC, umairzafar164 commented on src/modules/player/components/SKPlayer/components/SKIframe.tsx
> +      style={{
Moved to home module css file.

2022-09-02 14:14 UTC, umairzafar164 commented on src/modules/player/components/SKPlayer/components/SKVideo.tsx
> +  const { vidRef, index, playlist } = props;
Done.

2022-09-02 14:15 UTC, umairzafar164 commented on src/modules/player/components/SKPlayer/SKPlayer.tsx
> +        if (playlist.tag === "video") {
Yes, using switch case now with image tag as default return.

2022-09-07 11:59 UTC, shaheerizharReal approved these changes

2022-09-07 12:00 UTC, merged